/*******************************************************************************
 Source file for the Net Pres Certificate Store functions to work with Harmony


  Summary:


  Description:

*******************************************************************************/

/*
Copyright (C) 2015-2023, Microchip Technology Inc., and its subsidiaries. All rights reserved.

The software and documentation is provided by microchip and its contributors
"as is" and any express, implied or statutory warranties, including, but not
limited to, the implied warranties of merchantability, fitness for a particular
purpose and non-infringement of third party intellectual property rights are
disclaimed to the fullest extent permitted by law. In no event shall microchip
or its contributors be liable for any direct, indirect, incidental, special,
exemplary, or consequential damages (including, but not limited to, procurement
of substitute goods or services; loss of use, data, or profits; or business
interruption) however caused and on any theory of liability, whether in contract,
strict liability, or tort (including negligence or otherwise) arising in any way
out of the use of the software and documentation, even if advised of the
possibility of such damage.

Except as expressly permitted hereunder and subject to the applicable license terms
for any third-party software incorporated in the software and any applicable open
source software license terms, no license or other rights, whether express or
implied, are granted under any patent or other intellectual property rights of
Microchip or any third party.
*/

#include "net_pres/pres/net_pres_certstore.h"
#define USE_CERT_BUFFERS_2048
#include "cert_header.h"
/* Not generated by Harmony: extra root CA for the IoTConnect HTTPS endpoints. */
#include "iotc_ca_certs.h"

/* Trusted root CAs, one per certIndex.  The caller enumerates them starting at
 * index 0 until this function returns false.
 *
 *   0 : Starfield  -- AWS IoT Core (MQTT broker).
 *   1 : Go Daddy   -- *.iotconnect.io (discovery and identity REST APIs).
 */
bool NET_PRES_CertStoreGetCACerts(const uint8_t ** certPtr, int32_t * certSize, uint8_t certIndex)
{
    switch (certIndex)
    {
        case 0:
            *certPtr = app_client_cert_der_starfield_base;
            *certSize = sizeof_app_client_cert_der_starfield_base;
            return true;

        case 1:
            *certPtr = iotc_ca_godaddy_root_g2_der;
            *certSize = sizeof_iotc_ca_godaddy_root_g2_der;
            return true;

        default:
            break;
    }

    return false;
}
